development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: todo_list_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: todo_app_production
